// DATA: ISCI Raw Data
const D_I=[["CHIPL2515001T","Confident","TV","Postman Law","CHI","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515001T.mp4?alt=media"],
["CHIPL2515002T","Fast Results","TV","Postman Law","CHI","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515002T.mp4?alt=media"],
["CHIPL2515003T","Their Only Case","TV","Postman Law","CHI","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515003T.mp4?alt=media"],
["CHIPL2515004T","Elite Performance","TV","Postman Law","CHI","15","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515004T.mp4?alt=media"],
["CHIPL2515006T","Christmas 2025_15","TV","Postman Law","CHI","15","T",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515006T.mov?alt=media"],
["CHIPL2530001T","Elite","TV","Postman Law","CHI","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530001T.mp4?alt=media"],
["CHIPL2530002T","We'll Fight","TV","Postman Law","CHI","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530002T.mp4?alt=media"],
["CHIPL2530003T","Three Billion","TV","Postman Law","CHI","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530003T.mp4?alt=media"],
["CHIPL2530004T","We Care","TV","Postman Law","CHI","30","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530004T.mp4?alt=media"],
["CHIPL2530005T","Harvard","TV","Postman Law","CHI","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530005T.mov?alt=media"],
["CHIPL2560002T","Supreme Court","TV","Postman Law","CHI","60","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2560002T.mp4?alt=media"],
["CHIPL2615001T","Harvard","TV","Postman Law","CHI","15","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615001T.mov?alt=media"],
["CHIPL2560001T","Why Postman","TV","Postman Law","CHI","60","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2560001T.mp4?alt=media"],
["CHIPL2615007T","Justice & Representation","TV","Postman Law","CHI","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615007T.mp4?alt=media"],
["CHIPL2615008T","Legal Firepower","TV","Postman Law","CHI","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615008T.mp4?alt=media"],
["CHIPL2615009T","Warren's Story","TV","Postman Law","CHI","15","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615009T.mp4?alt=media"],
["CHIPL2615010T","Local Lawyers","TV","Postman Law","CHI","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615010T.mp4?alt=media"],
["CHIPL2630006T","Justice & Representation","TV","Postman Law","CHI","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630006T.mp4?alt=media"],
["CHIPL2630007T","Legal Firepower","TV","Postman Law","CHI","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630007T.mp4?alt=media"],
["CHIPL2630008T","Warren's Story","TV","Postman Law","CHI","30","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630008T.mp4?alt=media"],
["CHIPL2630009T","Local Lawyers","TV","Postman Law","CHI","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630009T.mp4?alt=media"],
["CHIPL2660003T","Harvard","TV","Postman Law","CHI","60","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2660003T.mov?alt=media"],
["CINPL2515001T","Confident","TV","Postman Law","CIN","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515001T.mp4?alt=media"],
["CINPL2515002T","Fast Results","TV","Postman Law","CIN","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515002T.mp4?alt=media"],
["CINPL2515003T","Their Only Case","TV","Postman Law","CIN","15","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515003T.mp4?alt=media"],
["CINPL2515004T","Elite Performance","TV","Postman Law","CIN","15","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515004T.mp4?alt=media"],
["CINPL2515006T","Christmas 2025_15","TV","Postman Law","CIN","15","T",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515006T.mov?alt=media"],
["CINPL2530001T","Elite","TV","Postman Law","CIN","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530001T.mp4?alt=media"],
["CINPL2530002T","We'll Fight","TV","Postman Law","CIN","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530002T.mp4?alt=media"],
["CINPL2530003T","Three Billion","TV","Postman Law","CIN","30","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530003T.mp4?alt=media"],
["CINPL2530004T","We Care","TV","Postman Law","CIN","30","T",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530004T.mp4?alt=media"],
["CINPL2560002T","Supreme Court","TV","Postman Law","CIN","60","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2560002T.mp4?alt=media"],
["CINPL2615001T","Harvard","TV","Postman Law","CIN","15","T",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615001T.mov?alt=media"],
["CINPL2560001T","Why Postman","TV","Postman Law","CIN","60","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2560001T.mp4?alt=media"],
["CINPL2615007T","Justice & Representation","TV","Postman Law","CIN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615007T.mp4?alt=media"],
["CINPL2615008T","Legal Firepower","TV","Postman Law","CIN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615008T.mp4?alt=media"],
["CINPL2615009T","Warren's Story","TV","Postman Law","CIN","15","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615009T.mp4?alt=media"],
["CINPL2615010T","Local Lawyers","TV","Postman Law","CIN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615010T.mp4?alt=media"],
["CINPL2630006T","Justice & Representation","TV","Postman Law","CIN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2630006T.mp4?alt=media"],
["CINPL2630007T","Legal Firepower","TV","Postman Law","CIN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2630007T.mp4?alt=media"],
["CINPL2630008T","Warren's Story","TV","Postman Law","CIN","30","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2630008T.mp4?alt=media"],
["CINPL2630009T","Local Lawyers","TV","Postman Law","CIN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2630009T.mp4?alt=media"],
["CINPL2660003T","Harvard","TV","Postman Law","CIN","60","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2660003T.mov?alt=media"],
["DENPL2515001T","Confident","TV","Postman Law","DEN","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515001T.mp4?alt=media"],
["DENPL2515002T","Fast Results","TV","Postman Law","DEN","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515002T.mp4?alt=media"],
["DENPL2515003T","Their Only Case","TV","Postman Law","DEN","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515003T.mp4?alt=media"],
["DENPL2515004T","Elite Performance","TV","Postman Law","DEN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515004T.mp4?alt=media"],
["DENPL2515005T","Harvard","TV","Postman Law","DEN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515005T.mp4?alt=media"],
["DENPL2515006T","Christmas 2025_15","TV","Postman Law","DEN","15","T",true,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515006T.mov?alt=media"],
["DENPL2530001T","Elite","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530001T.mp4?alt=media"],
["DENPL2530002T","We'll Fight","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530002T.mp4?alt=media"],
["DENPL2530003T","Three Billion","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530003T.mp4?alt=media"],
["DENPL2530004T","We Care","TV","Postman Law","DEN","30","T",true,"Personal Injury (General)",""],
["DENPL2530005T","Harvard","TV","Postman Law","DEN","30","T",true,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530005T.mov?alt=media"],
["DENPL2560001T","Why Postman","TV","Postman Law","DEN","60","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2560001T.mp4?alt=media"],
["DENPL2560002T","Supreme Court","TV","Postman Law","DEN","60","T",true,"",""],
["DENPL2615001T","Harvard","TV","Postman Law","DEN","15","T",true,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2615001T.mov?alt=media"],
["DENPL2615002T","Harvard_15","TV","Postman Law","DEN","15","T",true,"",""],
["DENPL2615003T","Confident_15","TV","Postman Law","DEN","15","T",true,"",""],
["DENPL2615004T","Elite Talent_15","TV","Postman Law","DEN","15","T",true,"",""],
["DENPL2615005T","Fast Results_15","TV","Postman Law","DEN","15","T",true,"",""],
["DENPL2615006T","Their Only Case_15","TV","Postman Law","DEN","15","T",true,"",""],
["DENPL2630001T","Harvard_30","TV","Postman Law","DEN","30","T",true,"",""],
["DENPL2630002T","Elite_30","TV","Postman Law","DEN","30","T",true,"",""],
["DENPL2630003T","We Care_30","TV","Postman Law","DEN","30","T",true,"",""],
["DENPL2630004T","We'll Fight _30","TV","Postman Law","DEN","30","T",true,"",""],
["DENPL2630005T","Three Billion_30","TV","Postman Law","DEN","30","T",true,"",""],
["DENPL2615007T","Justice & Representation","TV","Postman Law","DEN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2615007T.mp4?alt=media"],
["DENPL2615008T","Legal Firepower","TV","Postman Law","DEN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2615008T.mp4?alt=media"],
["DENPL2615009T","Warren's Story","TV","Postman Law","DEN","15","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2615009T.mp4?alt=media"],
["DENPL2615010T","Local Lawyers","TV","Postman Law","DEN","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2615010T.mp4?alt=media"],
["DENPL2630006T","Justice & Representation","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2630006T.mp4?alt=media"],
["DENPL2630007T","Legal Firepower","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2630007T.mp4?alt=media"],
["DENPL2630008T","Warren's Story","TV","Postman Law","DEN","30","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2630008T.mp4?alt=media"],
["DENPL2630009T","Local Lawyers","TV","Postman Law","DEN","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2630009T.mp4?alt=media"],
["MSPPL2515001T","Confident","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515001T.mp4?alt=media"],
["MSPPL2515002T","Fast Results","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515002T.mp4?alt=media"],
["MSPPL2515003T","Their Only Case","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515003T.mp4?alt=media"],
["MSPPL2515004T","Elite Performance","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515004T.mp4?alt=media"],
["MSPPL2515005T","Harvard","TV","Postman Law","MSP","15","T",true,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515005T.mov?alt=media"],
["MSPPL2515006T","Christmas 2025_15","TV","Postman Law","MSP","15","T",true,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515006T.mov?alt=media"],
["MSPPL2530001T","Elite","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530001T.mp4?alt=media"],
["MSPPL2530002T","We'll Fight","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530002T.mp4?alt=media"],
["MSPPL2530003T","Three Billion","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530003T.mp4?alt=media"],
["MSPPL2530004T","We Care","TV","Postman Law","MSP","30","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530004T.mp4?alt=media"],
["MSPPL2530005T","Harvard","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530005T.mov?alt=media"],
["MSPPL2560001T","Why Postman","TV","Postman Law","MSP","60","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2560001T.mp4?alt=media"],
["MSPPL2560002T","Supreme Court","TV","Postman Law","MSP","60","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2560002T.mp4?alt=media"],
["MSPPL2615001T","Harvard","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615001T.mov?alt=media"],
["MSPPL2615002T","Their Only Case","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615002T.mov?alt=media"],
["MSPPL2615003T","Fast Results","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615003T.mov?alt=media"],
["MSPPL2615004T","Elite Talent","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615004T.mov?alt=media"],
["MSPPL2615005T","Confident","TV","Postman Law","MSP","15","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615005T.mov?alt=media"],
["MSPPL2615006T","Building Trust Harvard","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615006T.mov?alt=media"],
["MSPPL2630001T","We've Deliver","TV","Postman Law","MSP","30","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630001T.mov?alt=media"],
["MSPPL2630002T","We'll Fight","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630002T.mov?alt=media"],
["MSPPL2630003T","We Care","TV","Postman Law","MSP","30","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630003T.mov?alt=media"],
["MSPPL2630004T","Elite Award Winning","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630004T.mov?alt=media"],
["MSPPL2630005T","Building Trust Harvard","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630005T.mov?alt=media"],
["MSPPL2615007T","Justice & Representation","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615007T.mp4?alt=media"],
["MSPPL2615008T","Legal Firepower","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615008T.mp4?alt=media"],
["MSPPL2615009T","Warren's Story","TV","Postman Law","MSP","15","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615009T.mp4?alt=media"],
["MSPPL2615010T","Local Lawyers","TV","Postman Law","MSP","15","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615010T.mp4?alt=media"],
["MSPPL2630006T","Justice & Representation","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630006T.mp4?alt=media"],
["MSPPL2630007T","Legal Firepower","TV","Postman Law","MSP","30","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630007T.mp4?alt=media"],
["MSPPL2630008T","Warren's Story","TV","Postman Law","MSP","30","T",true,"Testimonial","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630008T.mp4?alt=media"],
["MSPPL2630009T","Local Laywers","TV","Postman Law","MSP","30","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630009T.mp4?alt=media"],
["MSPPL2660001T","Why Postman","TV","Postman Law","MSP","60","T",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2660001T.mov?alt=media"],
["MSPPL2660002T","Supreme Court","TV","Postman Law","MSP","60","T",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2660002T.mov?alt=media"],
["CHIPL2530001D","Elite","Digital","Postman Law","CHI","30","D",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530001D.mp4?alt=media"],
["CHIPL2530002D","We'll Fight","Digital","Postman Law","CHI","30","D",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530002D.mp4?alt=media"],
["CHIPL2530003D","Three Billion","Digital","Postman Law","CHI","30","D",false,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530003D.mp4?alt=media"],
["CHIPL2530004D","We Care","Digital","Postman Law","CHI","30","D",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530004D.mp4?alt=media"],
["CINPL2530004D","We Care","Digital","Postman Law","CIN","30","D",true,"Personal Injury (General)",""],
["CINPL2530003D","Three Billion","Digital","Postman Law","CIN","30","D",true,"Brand",""],
["CINPL2530002D","We'll Fight","Digital","Postman Law","CIN","30","D",true,"Brand",""],
["CINPL2530001D","Elite","Digital","Postman Law","CIN","30","D",true,"Brand",""],
["DENPL2530004","We Care","Radio","Postman Law","DEN","30","",false,"Personal Injury (General)",""],
["DENPL2530003D","Three Billion","Digital","Postman Law","DEN","30","D",true,"Brand",""],
["DENPL2530001D","Elite","Digital","Postman Law","DEN","30","D",true,"Brand",""],
["DENPL2530002D","We'll Fight","Digital","Postman Law","DEN","30","D",true,"Brand",""],
["MSPPL2530004D","We Care","Digital","Postman Law","MSP","30","D",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530004D.mp4?alt=media"],
["MSPPL2530003D","Three Billion","Digital","Postman Law","MSP","30","D",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530003D.mp4?alt=media"],
["MSPPL2530002D","We'll Fight","Digital","Postman Law","MSP","30","D",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530002D.mp4?alt=media"],
["MSPPL2530001D","Elite","Digital","Postman Law","MSP","30","D",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530001D.mp4?alt=media"],
["CHIPL2515001R","Not Your Typical","Radio","Postman Law","CHI","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515001R.mp3?alt=media"],
["CHIPL2515002R","Really Need a Lawyer","Radio","Postman Law","CHI","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515002R.mp3?alt=media"],
["CHIPL2515003R","Holiday Stress","Radio","Postman Law","CHI","15","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515003R.mp3?alt=media"],
["CHIPL2515004R","Santa & PL Delivers","Radio","Postman Law","CHI","15","R",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515004R.mp3?alt=media"],
["CHIPL2530001R","Winning Matters","Radio","Postman Law","CHI","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530001R.mp3?alt=media"],
["CHIPL2530002R","Not Your Typical","Radio","Postman Law","CHI","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530002R.mp3?alt=media"],
["CHIPL2530003R","Change","Radio","Postman Law","CHI","30","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530003R.mp3?alt=media"],
["CHIPL2530004R","Really Need a Lawyer","Radio","Postman Law","CHI","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530004R.mp3?alt=media"],
["CHIPL2530005R","Santa & PL Delivers","Radio","Postman Law","CHI","30","R",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530005R.mp3?alt=media"],
["CHIPL2530006R","Holiday Stress","Radio","Postman Law","CHI","30","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530006R.mp3?alt=media"],
["CHIPL2615001R","To Do List","Radio","Postman Law","CHI","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615001R.mp3?alt=media"],
["CHIPL2615002R","We Fight","Radio","Postman Law","CHI","15","R",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615002R.mp3?alt=media"],
["CHIPL2630001R","To Do List","Radio","Postman Law","CHI","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630001R.mp3?alt=media"],
["CHIPL2630002R","We Fight","Radio","Postman Law","CHI","30","R",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630002R.mp3?alt=media"],
["CINPL2630002R","We Fight","Radio","Postman Law","CIN","30","R",true,"",""],
["CINPL2615002R","We Fight","Radio","Postman Law","CIN","15","R",true,"",""],
["CINPL2630001R","To Do List","Radio","Postman Law","CIN","30","R",true,"",""],
["CINPL2530006R","Holiday Stress","Radio","Postman Law","CIN","30","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530006R.mp3?alt=media"],
["CINPL2615001R","To Do List","Radio","Postman Law","CIN","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2615001R.mp3?alt=media"],
["CINPL2530005R","Santa & PL Delivers","Radio","Postman Law","CIN","30","R",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530005R.mp3?alt=media"],
["CINPL2530004R","Really Need A Lawyer","Radio","Postman Law","CIN","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530004R.mp3?alt=media"],
["CINPL2530002R","Not Your Typical","Radio","Postman Law","CIN","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530002R.mp3?alt=media"],
["CINPL2515004R","Santa & PL Delivers","Radio","Postman Law","CIN","15","R",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515004R.mp3?alt=media"],
["CINPL2515003R","Holiday Stress","Radio","Postman Law","CIN","15","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515003R.mp3?alt=media"],
["CINPL2515002R","Really Need A Lawyer","Radio","Postman Law","CIN","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515002R.mp3?alt=media"],
["CINPL2515001R","Not Your Typical","Radio","Postman Law","CIN","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515001R.mp3?alt=media"],
["DENPL2630002R","We Fight","Radio","Postman Law","DEN","30","R",true,"",""],
["DENPL2615002R","We Fight","Radio","Postman Law","DEN","15","R",true,"",""],
["DENPL2630001R","To Do List","Radio","Postman Law","DEN","30","R",true,"",""],
["DENPL2530005R","Santa & PL Delivers","Radio","Postman Law","DEN","30","R",false,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530005R.mp3?alt=media"],
["DENPL2530006R","Holiday Stress","Radio","Postman Law","DEN","30","R",false,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530006R.mp3?alt=media"],
["DENPL2615001R","To Do List","Radio","Postman Law","DEN","15","R",true,"",""],
["DENPL2530004R","Really Need A Lawyer","Radio","Postman Law","DEN","30","R",true,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530004R.mp3?alt=media"],
["DENPL2530002R","Not Your Typical","Radio","Postman Law","DEN","30","R",true,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530002R.mp3?alt=media"],
["DENPL2515004R","Santa & PL Delivers","Radio","Postman Law","DEN","15","R",false,"","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515004R.mp3?alt=media"],
["DENPL2515001R","Not Your Typical","Radio","Postman Law","DEN","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515001R.mp3?alt=media"],
["DENPL2515002R","Really Need A Lawyer","Radio","Postman Law","DEN","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515002R.mp3?alt=media"],
["DENPL2515003R","Holiday Stress","Radio","Postman Law","DEN","15","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515003R.mp3?alt=media"],
["MSPPL2630002R","We Fight","Radio","Postman Law","MSP","30","R",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630002R.mp3?alt=media"],
["MSPPL2615001R","To Do List","Radio","Postman Law","MSP","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615001R.mp3?alt=media"],
["MSPPL2615002R","We Fight","Radio","Postman Law","MSP","15","R",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615002R.mp3?alt=media"],
["MSPPL2630001R","To Do List","Radio","Postman Law","MSP","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630001R.mp3?alt=media"],
["MSPPL2530002R","Not Your Typical","Radio","Postman Law","MSP","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530002R.mp3?alt=media"],
["MSPPL2530004R","Really Need A Lawyer","Radio","Postman Law","MSP","30","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530004R.mp3?alt=media"],
["MSPPL2515002R","Really Need a Lawyer","Radio","Postman Law","MSP","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515002R.mp3?alt=media"],
["MSPPL2515001R","Not Your Typical","Radio","Postman Law","MSP","15","R",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515001R.mp3?alt=media"],
["MSPPL253006R","Holiday Stress","Radio","Postman Law","MSP","30","R",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL253006R.mp3?alt=media"],
["MSPPL253005R","Santa & PL Delivers","Radio","Postman Law","MSP","30","R",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL253005R.mp3?alt=media"],
["CHIPL2515001S","Not Your Typical","Streaming Audio","Postman Law","CHI","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515001S.mp3?alt=media"],
["CHIPL2515002S","Really Need a Lawyer","Streaming Audio","Postman Law","CHI","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515002S.mp3?alt=media"],
["CHIPL2515003S","Holiday Stress","Streaming Audio","Postman Law","CHI","15","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515003S.mp3?alt=media"],
["CHIPL2515004S","Santa & PL Delivers","Streaming Audio","Postman Law","CHI","15","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2515004S.mp3?alt=media"],
["CHIPL2530001S","Winning Matters","Streaming Audio","Postman Law","CHI","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530001S.mp3?alt=media"],
["CHIPL2530002S","Not Your Typical","Streaming Audio","Postman Law","CHI","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530002S.mp3?alt=media"],
["CHIPL2530003S","Change","Streaming Audio","Postman Law","CHI","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530003S.mp3?alt=media"],
["CHIPL2530004S","Really Need a Lawyer","Streaming Audio","Postman Law","CHI","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530004S.mp3?alt=media"],
["CHIPL2530005S","Santa & PL Delivers","Streaming Audio","Postman Law","CHI","30","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530005S.mp3?alt=media"],
["CHIPL2530006S","Holiday Stress","Streaming Audio","Postman Law","CHI","30","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2530006S.mp3?alt=media"],
["CHIPL2615001S","To Do List","Streaming Audio","Postman Law","CHI","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615001S.mp3?alt=media"],
["CHIPL2615002S","We Fight","Streaming Audio","Postman Law","CHI","15","S",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2615002S.mp3?alt=media"],
["CHIPL2630001S","To Do List","Streaming Audio","Postman Law","CHI","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630001S.mp3?alt=media"],
["CHIPL2630002S","We Fight","Streaming Audio","Postman Law","CHI","30","S",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCHIPL2630002S.mp3?alt=media"],
["CINPL2515001S","Not Your Typical","Streaming Audio","Postman Law","CIN","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515001S.mp3?alt=media"],
["CINPL2515002S","Really Need A Lawyer","Streaming Audio","Postman Law","CIN","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515002S.mp3?alt=media"],
["CINPL2515003S","Holiday Stress","Streaming Audio","Postman Law","CIN","15","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515003S.mp3?alt=media"],
["CINPL2515004S","Santa & PL Delivers","Streaming Audio","Postman Law","CIN","15","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2515004S.mp3?alt=media"],
["CINPL2530002S","Not Your Typical","Streaming Audio","Postman Law","CIN","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530002S.mp3?alt=media"],
["CINPL2530004S","Really Need A Lawyer","Streaming Audio","Postman Law","CIN","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530004S.mp3?alt=media"],
["CINPL2530005S","Santa & PL Delivers","Streaming Audio","Postman Law","CIN","30","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530005S.mp3?alt=media"],
["CINPL2530006S","Holiday Stress","Streaming Audio","Postman Law","CIN","30","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FCINPL2530006S.mp3?alt=media"],
["CINPL2630001S","To Do List","Streaming Audio","Postman Law","CIN","30","S",true,"",""],
["CINPL2630002S","We Fight","Streaming Audio","Postman Law","CIN","30","S",true,"",""],
["DENPL2515001S","Not Your Typical","Streaming Audio","Postman Law","DEN","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515001S.mp3?alt=media"],
["DENPL2515002S","Really Need A Lawyer","Streaming Audio","Postman Law","DEN","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515002S.mp3?alt=media"],
["DENPL2515003S","Holiday Stress","Streaming Audio","Postman Law","DEN","15","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515003S.mp3?alt=media"],
["DENPL2515004S","Santa & PL Delivers","Streaming Audio","Postman Law","DEN","15","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2515004S.mp3?alt=media"],
["DENPL2530002S","Not Your Typical","Streaming Audio","Postman Law","DEN","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530002S.mp3?alt=media"],
["DENPL2530004S","Really Need A Lawyer","Streaming Audio","Postman Law","DEN","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530004S.mp3?alt=media"],
["DENPL2530005S","Santa & PL Delivers","Streaming Audio","Postman Law","DEN","30","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530005S.mp3?alt=media"],
["DENPL2530006S","Holiday Stress","Streaming Audio","Postman Law","DEN","30","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FDENPL2530006S.mp3?alt=media"],
["DENPL2615001S","To Do List","Streaming Audio","Postman Law","DEN","15","S",true,"Personal Injury (General)",""],
["DENPL2615002S","We Fight","Streaming Audio","Postman Law","DEN","15","S",true,"",""],
["DENPL2630001S","To Do List","Streaming Audio","Postman Law","DEN","30","S",true,"",""],
["DENPL2630002S","We Fight","Streaming Audio","Postman Law","DEN","30","S",true,"",""],
["MSPPL2515001S","Not Your Typical","Streaming Audio","Postman Law","MSP","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515001S.mp3?alt=media"],
["MSPPL2515002S","Really Need A Lawyer","Streaming Audio","Postman Law","MSP","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2515002S.mp3?alt=media"],
["MSPPL2530002S","Not Your Typical","Streaming Audio","Postman Law","MSP","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530002S.mp3?alt=media"],
["MSPPL2530004S","Really Need A Lawyer","Streaming Audio","Postman Law","MSP","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530004S.mp3?alt=media"],
["MSPPL2530005S","Santa & PL Delivers","Streaming Audio","Postman Law","MSP","30","S",false,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530005S.mp3?alt=media"],
["MSPPL2530006S","Holiday Stress","Streaming Audio","Postman Law","MSP","30","S",false,"Holiday/Seasonal","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2530006S.mp3?alt=media"],
["MSPPL2615001S","To Do List","Streaming Audio","Postman Law","MSP","15","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615001S.mp3?alt=media"],
["MSPPL2615002S","We Fight","Streaming Audio","Postman Law","MSP","15","S",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2615002S.mp3?alt=media"],
["MSPPL2630001S","To Do List","Streaming Audio","Postman Law","MSP","30","S",true,"Personal Injury (General)","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630001S.mp3?alt=media"],
["MSPPL2630002S","We Fight","Streaming Audio","Postman Law","MSP","30","S",true,"Brand","https://firebasestorage.googleapis.com/v0/b/atti-coordination.firebasestorage.app/o/creative%2FMSPPL2630002S.mp3?alt=media"],
["BRMWK2515007T","Branding Legacy_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2515008T","Commercial Accident_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2515010T","Different_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2515012T","Christmas 2025_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2530006T","Happy Thanksgiving","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2530007T","Different_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2530009T","Christmas 2025_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2604001T","Personal_04","TV","Wettermark Keith","BRM","04","T",true,"",""],
["BRMWK2605001T","Car Wreck_05","TV","Wettermark Keith","BRM","05","T",true,"",""],
["BRMWK2605002T","Premise Injury_5","TV","Wettermark Keith","BRM","05","T",true,"",""],
["BRMWK2610001T","Car Wreck_10","TV","Wettermark Keith","BRM","10","T",true,"",""],
["BRMWK2610002T","Premise Injury 10","TV","Wettermark Keith","BRM","10","T",true,"",""],
["BRMWK2615001T","Car Wreck_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615002T","Weekends 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615003T","Trucking Two_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615004T","Premise Injury 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615006T","Working Man_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615007T","Mother's Wreck_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615008T","Trucking One_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615009T","Commercial Vehicle_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615010T","Strength in Confidence 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615011T","More To Us 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615012T","On The Job Injury 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615013T","Premises Liability 15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2615014T","Auto Accident_15","TV","Wettermark Keith","BRM","15","T",true,"",""],
["BRMWK2630001T","Local Lawyers_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630002T","Award Winning_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630004T","Personal_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630006T","Weekends 30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630010T","Strength in Confidence_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630014T","Trucking Two_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["BRMWK2630015T","Auto Accident_30","TV","Wettermark Keith","BRM","30","T",true,"",""],
["CHAWK2515007T","Branding Legacy_15","TV","Wettermark Keith","CHA","15","T",true,"Brand",""],
["CHAWK2515008T","Commercial Accident_15","TV","Wettermark Keith","CHA","15","T",true,"Trucking/Commercial",""],
["CHAWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","CHA","15","T",true,"Auto Accidents",""],
["CHAWK2515010T","Different_15","TV","Wettermark Keith","CHA","15","T",true,"Brand",""],
["CHAWK2515011T","Trucking One_15","TV","Wettermark Keith","CHA","15","T",true,"Trucking/Commercial",""],
["CHAWK2515012T","Christmas 2025_15","TV","Wettermark Keith","CHA","15","T",true,"Holiday/Seasonal",""],
["CHAWK2530006T","Happy Thanksgiving","TV","Wettermark Keith","CHA","30","T",true,"Brand",""],
["CHAWK2530007T","Different_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2530009T","Christmas 2025_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2604001T","Personal_04","TV","Wettermark Keith","CHA","04","T",true,"",""],
["CHAWK2605001T","Car Wreck_05","TV","Wettermark Keith","CHA","05","T",true,"",""],
["CHAWK2605002T","Premise Injury_05","TV","Wettermark Keith","CHA","05","T",true,"",""],
["CHAWK2610001T","Car Wreck_10","TV","Wettermark Keith","CHA","10","T",true,"",""],
["CHAWK2610002T","Premise Injury_10","TV","Wettermark Keith","CHA","10","T",true,"",""],
["CHAWK2615002T","Weekends_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615003T","Trucking Two_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615004T","Premise Injury_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615006T","Working Man_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615007T","Mother's Wreck_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615009T","Commercial Vehicle_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615010T","Strength in Confidence_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615011T","More To Us_15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2615012T","On The Job Injury 15","TV","Wettermark Keith","CHA","15","T",true,"",""],
["CHAWK2630002T","Award Winning_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630004T","Personal_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630005T","Working Man_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630006T","Weekends_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630010T","Strength in Confidence_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["CHAWK2630014T","Trucking Two_30","TV","Wettermark Keith","CHA","30","T",true,"",""],
["DHNWK2515007T","Branding Legacy_15","TV","Wettermark Keith","DHN","15","T",true,"Brand",""],
["DHNWK2515008T","Commercial Accident_15","TV","Wettermark Keith","DHN","15","T",true,"Trucking/Commercial",""],
["DHNWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","DHN","15","T",true,"Auto Accidents",""],
["DHNWK2515010T","Different_15","TV","Wettermark Keith","DHN","15","T",true,"Brand",""],
["DHNWK2515011T","Trucking One_15","TV","Wettermark Keith","DHN","15","T",true,"Trucking/Commercial",""],
["DHNWK2515012T","Christmas 2025_15","TV","Wettermark Keith","DHN","15","T",true,"Holiday/Seasonal",""],
["DHNWK2530006T","Happy Thanksgiving","TV","Wettermark Keith","DHN","30","T",true,"Holiday/Seasonal",""],
["DHNWK2530008T","Different_30","TV","Wettermark Keith","DHN","30","T",true,"Brand",""],
["DHNWK2530009T","Christmas 2025_30","TV","Wettermark Keith","DHN","30","T",true,"Holiday/Seasonal",""],
["DHNWK2604001T","Personal_04","TV","Wettermark Keith","DHN","04","T",true,"Brand",""],
["DHNWK2605001T","Car Wreck_05","TV","Wettermark Keith","DHN","05","T",true,"Auto Accidents",""],
["DHNWK2605002T","Premise Injury_5","TV","Wettermark Keith","DHN","05","T",true,"Premises Liability",""],
["DHNWK2610001T","Car Wreck_10","TV","Wettermark Keith","DHN","10","T",true,"Auto Accidents",""],
["DHNWK2610002T","Premise Injury_10","TV","Wettermark Keith","DHN","10","T",true,"Premises Liability",""],
["DHNWK2615001T","Car Wreck_15","TV","Wettermark Keith","DHN","15","T",true,"Auto Accidents",""],
["DHNWK2615002T","Weekends_15","TV","Wettermark Keith","DHN","15","T",true,"Brand",""],
["DHNWK2615004T","Premise Injury_15","TV","Wettermark Keith","DHN","15","T",true,"Premises Liability",""],
["DHNWK2615006T","Working Man_15","TV","Wettermark Keith","DHN","15","T",true,"Workers Comp",""],
["DHNWK2615007T","Mother's Wreck 15","TV","Wettermark Keith","DHN","15","T",true,"Auto Accidents",""],
["DHNWK2615009T","Commercial Vehicle_15","TV","Wettermark Keith","DHN","15","T",true,"Trucking/Commercial",""],
["DHNWK2615010T","Strength in Confidence 15","TV","Wettermark Keith","DHN","15","T",true,"Brand",""],
["DHNWK2615011T","More To Us 15","TV","Wettermark Keith","DHN","15","T",true,"Brand",""],
["DHNWK2615012T","On The Job Injury 15","TV","Wettermark Keith","DHN","15","T",true,"Workers Comp",""],
["DHNWK2615013T","Premises Liability 15","TV","Wettermark Keith","DHN","15","T",true,"Premises Liability",""],
["DHNWK2615014T","Auto Accident_15","TV","Wettermark Keith","DHN","15","T",true,"Auto Accidents",""],
["DHNWK2630002T","Award Winning_30","TV","Wettermark Keith","DHN","30","T",true,"Brand",""],
["DHNWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","DHN","30","T",true,"Auto Accidents",""],
["DHNWK2630004T","Personal_30","TV","Wettermark Keith","DHN","30","T",true,"Brand",""],
["DHNWK2630005T","Working Man_30","TV","Wettermark Keith","DHN","30","T",true,"Workers Comp",""],
["DHNWK2630006T","Weekends_30","TV","Wettermark Keith","DHN","30","T",true,"Brand",""],
["DHNWK2630010T","Strength in Confidence 30","TV","Wettermark Keith","DHN","30","T",true,"Brand",""],
["DHNWK2630013T","Insurance Experts 30","TV","Wettermark Keith","DHN","30","T",true,"Personal Injury (General)",""],
["HSVWK2515007T","Branding Legacy_15","TV","Wettermark Keith","HSV","15","T",true,"Brand",""],
["HSVWK2515008T","Commercial Accident_15","TV","Wettermark Keith","HSV","15","T",true,"Trucking/Commercial",""],
["HSVWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","HSV","15","T",true,"Auto Accidents",""],
["HSVWK2515010T","Different_15","TV","Wettermark Keith","HSV","15","T",true,"Brand",""],
["HSVWK2515010T","Weekend_15","TV","Wettermark Keith","HSV","15","T",true,"Brand",""],
["HSVWK2515012T","Christmas 2025_15","TV","Wettermark Keith","HSV","15","T",true,"Holiday/Seasonal",""],
["HSVWK2530006T","Happy Thanksgiving","TV","Wettermark Keith","HSV","30","T",true,"Brand",""],
["HSVWK2530007T","Different_30","TV","Wettermark Keith","HSV","30","T",true,"",""],
["HSVWK2530009T","Christmas 2025_30","TV","Wettermark Keith","HSV","30","T",true,"Holiday/Seasonal",""],
["HSVWK2604001T","Personal_04","TV","Wettermark Keith","HSV","04","T",true,"Brand",""],
["HSVWK2605001T","Car Wreck_05","TV","Wettermark Keith","HSV","05","T",true,"Auto Accidents",""],
["HSVWK2605002T","Premise Injury_05","TV","Wettermark Keith","HSV","05","T",true,"Premises Liability",""],
["HSVWK2610001T","Car Wreck_10","TV","Wettermark Keith","HSV","10","T",true,"Auto Accidents",""],
["HSVWK2610002T","Premise Injury_10","TV","Wettermark Keith","HSV","10","T",true,"Premises Liability",""],
["HSVWK2615001T","Car Wreck_15","TV","Wettermark Keith","HSV","15","T",true,"Auto Accidents",""],
["HSVWK2615002T","Weekend_15","TV","Wettermark Keith","HSV","15","T",true,"Brand",""],
["HSVWK2615004T","Premise Injury_15","TV","Wettermark Keith","HSV","15","T",true,"Premises Liability",""],
["HSVWK2615006T","Working Man_15","TV","Wettermark Keith","HSV","15","T",true,"Workers Comp",""],
["HSVWK2615007T","Mother's Wreck_15","TV","Wettermark Keith","HSV","15","T",true,"Auto Accidents",""],
["HSVWK2615008T","Trucking One_15","TV","Wettermark Keith","HSV","15","T",true,"Trucking/Commercial",""],
["HSVWK2615010T","Strength in Confidence 15","TV","Wettermark Keith","HSV","15","T",true,"Brand",""],
["HSVWK2615011T","More To Us 15","TV","Wettermark Keith","HSV","15","T",true,"",""],
["HSVWK2615012T","On The Job Injury 15","TV","Wettermark Keith","HSV","15","T",true,"Workers Comp",""],
["HSVWK2615013T","Premises Liability 15","TV","Wettermark Keith","HSV","15","T",true,"Premises Liability",""],
["HSVWK2615014T","Auto Accident_15","TV","Wettermark Keith","HSV","15","T",true,"Auto Accidents",""],
["HSVWK2630002T","Award Winning_30","TV","Wettermark Keith","HSV","30","T",true,"Brand",""],
["HSVWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","HSV","30","T",true,"Auto Accidents",""],
["HSVWK2630004T","Personal _30","TV","Wettermark Keith","HSV","30","T",true,"Brand",""],
["HSVWK2630005T","Working Man_30","TV","Wettermark Keith","HSV","30","T",true,"Workers Comp",""],
["HSVWK2630006T","Weekends_30","TV","Wettermark Keith","HSV","30","T",true,"Brand",""],
["HSVWK2630010T","Strength in Confidence 30","TV","Wettermark Keith","HSV","30","T",true,"Brand",""],
["HSVWK2630012T","On The Job Injury 30","TV","Wettermark Keith","HSV","30","T",true,"",""],
["KNXWK2515012T","Christmas 2025_15","TV","Wettermark Keith","KNX","15","T",true,"Holiday/Seasonal",""],
["KNXWK2515007T","Branding Legacy_15","TV","Wettermark Keith","KNX","15","T",true,"Brand",""],
["KNXWK2515008T","Commercial Accident_15","TV","Wettermark Keith","KNX","15","T",true,"Trucking/Commercial",""],
["KNXWK2515009T","Distracted Cell Phones\u00a0_15","TV","Wettermark Keith","KNX","15","T",true,"Auto Accidents",""],
["KNXWK2515010T","Different_15","TV","Wettermark Keith","KNX","15","T",true,"Brand",""],
["KNXWK2530006T","Happy Thanksgiving","TV","Wettermark Keith","KNX","30","T",true,"Brand",""],
["KNXWK2530007T","Different_30","TV","Wettermark Keith","KNX","30","T",true,"",""],
["KNXWK2530009T","Christmas 2025_30","TV","Wettermark Keith","KNX","30","T",true,"Holiday/Seasonal",""],
["KNXWK2604001T","Personal_04","TV","Wettermark Keith","KNX","04","T",true,"Brand",""],
["KNXWK2605001T","Car Wreck_05","TV","Wettermark Keith","KNX","05","T",true,"Auto Accidents",""],
["KNXWK2605002T","Premise Injury_05","TV","Wettermark Keith","KNX","05","T",true,"Premises Liability",""],
["KNXWK2610001T","Car Wreck_10","TV","Wettermark Keith","KNX","10","T",true,"Auto Accidents",""],
["KNXWK2610002T","Premise Injury_10","TV","Wettermark Keith","KNX","10","T",true,"Premises Liability",""],
["KNXWK2615001T","Car Wreck_15","TV","Wettermark Keith","KNX","15","T",true,"Auto Accidents",""],
["KNXWK2615002T","Weekends_15","TV","Wettermark Keith","KNX","15","T",true,"Brand",""],
["KNXWK2615003T","Trucking Two_15","TV","Wettermark Keith","KNX","15","T",true,"Trucking/Commercial",""],
["KNXWK2615004T","Premise Injury_15","TV","Wettermark Keith","KNX","15","T",true,"Premises Liability",""],
["KNXWK2615006T","Working Man_15","TV","Wettermark Keith","KNX","15","T",true,"Workers Comp",""],
["KNXWK2615007T","Mother's Wreck_15","TV","Wettermark Keith","KNX","15","T",true,"Auto Accidents",""],
["KNXWK2615008T","Trucking One_15","TV","Wettermark Keith","KNX","15","T",true,"Trucking/Commercial",""],
["KNXWK2615009T","Commercial Vehicle_15","TV","Wettermark Keith","KNX","15","T",true,"",""],
["KNXWK2615010T","Strength in Confidence 15","TV","Wettermark Keith","KNX","15","T",true,"Brand",""],
["KNXWK2615011T","More To Us 15","TV","Wettermark Keith","KNX","15","T",true,"",""],
["KNXWK2615012T","On The Job Injury 15","TV","Wettermark Keith","KNX","15","T",true,"Workers Comp",""],
["KNXWK2630002T","Award Winning","TV","Wettermark Keith","KNX","30","T",true,"Brand",""],
["KNXWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","KNX","30","T",true,"Auto Accidents",""],
["KNXWK2630004T","Personal_30","TV","Wettermark Keith","KNX","30","T",true,"Brand",""],
["KNXWK2630005T","Working Man_30","TV","Wettermark Keith","KNX","30","T",true,"Workers Comp",""],
["KNXWK2630006T","Weekends_30","TV","Wettermark Keith","KNX","30","T",true,"Brand",""],
["KNXWK2630010T","Strength in Confidence 30","TV","Wettermark Keith","KNX","30","T",true,"Brand",""],
["KNXWK2630014T","Trucking Two_30","TV","Wettermark Keith","KNX","30","T",true,"",""],
["MTGWK2515007T","Branding Legacy_15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2515007T","Branding Legacy_15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2515008T","Commercial Accident_15","TV","Wettermark Keith","MTG","15","T",true,"Trucking/Commercial",""],
["MTGWK2515008T","Commercial Accident_15","TV","Wettermark Keith","MTG","15","T",true,"Trucking/Commercial",""],
["MTGWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","MTG","15","T",true,"Auto Accidents",""],
["MTGWK2515009T","Distracted Cell Phones_15","TV","Wettermark Keith","MTG","15","T",true,"Auto Accidents",""],
["MTGWK2515010T","Different_15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2515010T","Different_15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2515012T","Christmas 2025_15","TV","Wettermark Keith","MTG","15","T",true,"Holiday/Seasonal",""],
["MTGWK2530007T","Different_30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2530007T","Different_30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2530009T","Christmas 2025_30","TV","Wettermark Keith","MTG","30","T",true,"Holiday/Seasonal",""],
["MTGWK2604001T","Personal_04","TV","Wettermark Keith","MTG","04","T",true,"Brand",""],
["MTGWK2605001T","Car Wreck_05","TV","Wettermark Keith","MTG","05","T",true,"Auto Accidents",""],
["MTGWK2605002T","Premise Injury_05","TV","Wettermark Keith","MTG","05","T",true,"Premises Liability",""],
["MTGWK2610001T","Car Wreck_10","TV","Wettermark Keith","MTG","10","T",true,"Auto Accidents",""],
["MTGWK2610002T","Premise_Injury_10","TV","Wettermark Keith","MTG","10","T",true,"Premises Liability",""],
["MTGWK2615001T","Car Wreck_15","TV","Wettermark Keith","MTG","15","T",true,"Auto Accidents",""],
["MTGWK2615002T","Weekends_15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2615003T","Trucking Two-15","TV","Wettermark Keith","MTG","15","T",true,"Trucking/Commercial",""],
["MTGWK2615004T","Premise Injury_15","TV","Wettermark Keith","MTG","15","T",true,"Premises Liability",""],
["MTGWK2615006T","Working Man_15","TV","Wettermark Keith","MTG","15","T",true,"Workers Comp",""],
["MTGWK2615007T","Mother's Wreck 15","TV","Wettermark Keith","MTG","15","T",true,"Auto Accidents",""],
["MTGWK2615008T","Trucking One_15","TV","Wettermark Keith","MTG","15","T",true,"Trucking/Commercial",""],
["MTGWK2615009T","Commercial Vehicle_15","TV","Wettermark Keith","MTG","15","T",true,"Trucking/Commercial",""],
["MTGWK2615010T","Strength in Confidence 15","TV","Wettermark Keith","MTG","15","T",true,"Brand",""],
["MTGWK2615012T","On The Job Injury 15","TV","Wettermark Keith","MTG","15","T",true,"Workers Comp",""],
["MTGWK2615013T","Premises Liability 15","TV","Wettermark Keith","MTG","15","T",true,"Premises Liability",""],
["MTGWK2615013T","Premises Liability 15","TV","Wettermark Keith","MTG","15","T",true,"Premises Liability",""],
["MTGWK2615014T","Auto Accident_15","TV","Wettermark Keith","MTG","15","T",true,"Auto Accidents",""],
["MTGWK2630002T","Award Winning_30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2630003T","Mother's Wreck_30","TV","Wettermark Keith","MTG","30","T",true,"Auto Accidents",""],
["MTGWK2630004T","Personal_30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2630005T","Working Man_30","TV","Wettermark Keith","MTG","30","T",true,"Workers Comp",""],
["MTGWK2630006T","Weekends 30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2630010T","Strength in Confidence 30","TV","Wettermark Keith","MTG","30","T",true,"Brand",""],
["MTGWK2630012T","On The Job Injury 30","TV","Wettermark Keith","MTG","30","T",true,"Workers Comp",""],
["BRMWK2615002R","Twenty Years_15","Radio","Wettermark Keith","BRM","15","R",true,"Personal Injury (General)",""],
["BRMWK2615003R","Right Lawyer_15","Radio","Wettermark Keith","BRM","15","R",true,"Personal Injury (General)",""],
["BRMWK2615004R","Case Type; Who We Help_15","Radio","Wettermark Keith","BRM","15","R",true,"Personal Injury (General)",""],
["BRMWK2615005R","How The Process Works_15","Radio","Wettermark Keith","BRM","15","R",true,"Personal Injury (General)",""],
["BRMWK2630001R","Blue Collar Roots_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630002R","People Over Size_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630003R","Mom_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630004R","Right Lawyer _30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630005R","Twenty Years_V1_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630006R","Twenty Years_V2_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630007R","Case Type; Who We Help_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["BRMWK2630008R","How The Process Works_30","Radio","Wettermark Keith","BRM","30","R",true,"Personal Injury (General)",""],
["DHNWK2615002R","Twenty Years_15","Radio","Wettermark Keith","DHN","15","R",true,"Personal Injury (General)",""],
["DHNWK2615003R","Right Lawyer_15","Radio","Wettermark Keith","DHN","15","R",true,"Personal Injury (General)",""],
["DHNWK2615004R","Case Type; Who We Help_15","Radio","Wettermark Keith","DHN","15","R",true,"Personal Injury (General)",""],
["DHNWK2615005R","How The Process Works_15","Radio","Wettermark Keith","DHN","15","R",true,"Personal Injury (General)",""],
["DHNWK2630001R","Blue Collar Roots_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630002R","People Over Size_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630003R","Mom_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630004R","Right Lawyer _30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630005R","Twenty Years_V1_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630006R","Twenty Years_V2_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630007R","Case Type; Who We Help_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["DHNWK2630008R","How The Process Works_30","Radio","Wettermark Keith","DHN","30","R",true,"Personal Injury (General)",""],
["HSVWK2615002R","Twenty Years_15","Radio","Wettermark Keith","HSV","15","R",true,"Personal Injury (General)",""],
["HSVWK2615003R","Right Lawyer_15","Radio","Wettermark Keith","HSV","15","R",true,"Personal Injury (General)",""],
["HSVWK2615004R","Case Type; Who We Help_15","Radio","Wettermark Keith","HSV","15","R",true,"Personal Injury (General)",""],
["HSVWK2615005R","How The Process Works_15","Radio","Wettermark Keith","HSV","15","R",true,"Personal Injury (General)",""],
["HSVWK2630001R","Blue Collar Roots_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630002R","People Over Size_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630003R","Mom_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630004R","Right Lawyer _30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630005R","Twenty Years_V1_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630006R","Twenty Years_V2_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630007R","Case Type; Who We Help_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["HSVWK2630008R","How The Process Works_30","Radio","Wettermark Keith","HSV","30","R",true,"Personal Injury (General)",""],
["MTGWK2615002R","Twenty Years_15","Radio","Wettermark Keith","MTG","15","R",true,"Personal Injury (General)",""],
["MTGWK2615003R","Right Lawyer_15","Radio","Wettermark Keith","MTG","15","R",true,"Personal Injury (General)",""],
["MTGWK2615004R","Case Type; Who We Help_15","Radio","Wettermark Keith","MTG","15","R",true,"Personal Injury (General)",""],
["MTGWK2615005R","How The Process Works_15","Radio","Wettermark Keith","MTG","15","R",true,"Personal Injury (General)",""],
["MTGWK2630001R","Blue Collar Roots_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630002R","People Over Size_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630003R","Mom_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630004R","Right Lawyer _30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630005R","Twenty Years_V1_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630006R","Twenty Years_V2_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630007R","Case Type; Who We Help_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["MTGWK2630008R","How The Process Works_30","Radio","Wettermark Keith","MTG","30","R",true,"Personal Injury (General)",""],
["BRMWK26SP001O","Local","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP002O","Local Shield","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP003O","H2H CK","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP004O","H2H Shield","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP005O","Injured H2H","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP006O","Injured IA","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["BRMWK26SP008O","Injured Skyline","OOH","Wettermark Keith","BRM","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP001O","Local","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP002O","Local Shield","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP003O","H2H CK","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP004O","H2H Shield","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP005O","Injured H2H","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP006O","Injured IA","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["GADWK26SP007O","Southern Justice","OOH","Wettermark Keith","GAD","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP001O","Local","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP002O","Local Shield","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP003O","H2H CK","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP004O","H2H Shield","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP005O","Injured H2H","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP006O","Injured IA","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["KNXWK26SP007O","Southern Justice","OOH","Wettermark Keith","KNX","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP001O","Local","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP002O","Local Shield","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP003O","H2H CK","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP004O","H2H Shield","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP005O","Injured H2H","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP006O","Injured IA","OOH","Wettermark Keith","MTG","SP","O",true,"Personal Injury (General)",""],
["MTGWK26SP007O","Southern Justice","OOH","Wettermark Keith","MTG","SP","O",true,"Brand",""],
["CHIPL2660004T","Why Postman_60","TV","Postman Law","CHI","60","T",true,"Brand",""],
["CHIPL2660005T","Supreme Court_60","TV","Postman Law","CHI","60","T",true,"Brand",""],
["CHIPL2630010T","Justice & Representation_30","TV","Postman Law","CHI","30","T",true,"Brand",""],
["CHIPL2630011T","Legal Firepower_30","TV","Postman Law","CHI","30","T",true,"Brand",""],
["CHIPL2630012T","Local Lawyers_30","TV","Postman Law","CHI","30","T",true,"Brand",""],
["CHIPL2630013T","Warren's Story_30","TV","Postman Law","CHI","30","T",true,"Testimonial",""],
["CHIPL2615011T","Justice & Representation_15","TV","Postman Law","CHI","15","T",true,"Brand",""],
["CHIPL2615012T","Legal Firepower_15","TV","Postman Law","CHI","15","T",true,"Brand",""],
["CHIPL2615013T","Local Lawyers_15","TV","Postman Law","CHI","15","T",true,"Brand",""],
["CHIPL2615014T","Warren's Story_15","TV","Postman Law","CHI","15","T",true,"Testimonial",""],
["CINPL2660004T","Why Postman_60","TV","Postman Law","CIN","60","T",true,"Brand",""],
["CINPL2660005T","Supreme Court_60","TV","Postman Law","CIN","60","T",true,"Brand",""],
["CINPL2630010T","Justice & Representation_30","TV","Postman Law","CIN","30","T",true,"Brand",""],
["CINPL2630011T","Legal Firepower_30","TV","Postman Law","CIN","30","T",true,"Brand",""],
["CINPL2630012T","Local Lawyers_30","TV","Postman Law","CIN","30","T",true,"Brand",""],
["CINPL2630013T","Warren's Story_30","TV","Postman Law","CIN","30","T",true,"Testimonial",""],
["CINPL2615011T","Justice & Representation_15","TV","Postman Law","CIN","15","T",true,"Brand",""],
["CINPL2615012T","Legal Firepower_15","TV","Postman Law","CIN","15","T",true,"Brand",""],
["CINPL2615013T","Local Lawyers_15","TV","Postman Law","CIN","15","T",true,"Brand",""],
["CINPL2615014T","Warren's Story_15","TV","Postman Law","CIN","15","T",true,"Testimonial",""],
["DENPL2660004T","Why Postman_60","TV","Postman Law","DEN","60","T",true,"Brand",""],
["DENPL2660005T","Supreme Court_60","TV","Postman Law","DEN","60","T",true,"Brand",""],
["DENPL2630010T","Justice & Representation_30","TV","Postman Law","DEN","30","T",true,"Brand",""],
["DENPL2630011T","Legal Firepower_30","TV","Postman Law","DEN","30","T",true,"Brand",""],
["DENPL2630012T","Local Lawyers_30","TV","Postman Law","DEN","30","T",true,"Brand",""],
["DENPL2630013T","Warren's Story_30","TV","Postman Law","DEN","30","T",true,"Testimonial",""],
["DENPL2615011T","Justice & Representation_15","TV","Postman Law","DEN","15","T",true,"Brand",""],
["DENPL2615012T","Legal Firepower_15","TV","Postman Law","DEN","15","T",true,"Brand",""],
["DENPL2615013T","Local Lawyers_15","TV","Postman Law","DEN","15","T",true,"Brand",""],
["DENPL2615014T","Warren's Story_15","TV","Postman Law","DEN","15","T",true,"Testimonial",""],
["MSPPL2660004T","Why Postman_60","TV","Postman Law","MSP","60","T",true,"Brand",""],
["MSPPL2660005T","Supreme Court_60","TV","Postman Law","MSP","60","T",true,"Brand",""],
["MSPPL2630010T","Justice & Representation_30","TV","Postman Law","MSP","30","T",true,"Brand",""],
["MSPPL2630011T","Legal Firepower_30","TV","Postman Law","MSP","30","T",true,"Brand",""],
["MSPPL2630012T","Local Lawyers_30","TV","Postman Law","MSP","30","T",true,"Brand",""],
["MSPPL2630013T","Warren's Story_30","TV","Postman Law","MSP","30","T",true,"Testimonial",""],
["MSPPL2615011T","Justice & Representation_15","TV","Postman Law","MSP","15","T",true,"Brand",""],
["MSPPL2615012T","Legal Firepower_15","TV","Postman Law","MSP","15","T",true,"Brand",""],
["MSPPL2615013T","Local Lawyers_15","TV","Postman Law","MSP","15","T",true,"Brand",""],
["MSPPL2615014T","Warren's Story_15","TV","Postman Law","MSP","15","T",true,"Testimonial",""],
["CHIPL2630007R","Catching Curveballs_30","Radio","Postman Law","CHI","30","R",true,"Brand",""],
["CINPL2630007R","Catching Curveballs_30","Radio","Postman Law","CIN","30","R",true,"Brand",""],
["DENPL2630007R","Catching Curveballs_30","Radio","Postman Law","DEN","30","R",true,"Brand",""],
["MSPPL2630007R","Catching Curveballs_30","Radio","Postman Law","MSP","30","R",true,"Brand",""],
["CHIPL2630007S","Catching Curveballs_30","Streaming Audio","Postman Law","CHI","30","S",true,"Brand",""],
["CINPL2630007S","Catching Curveballs_30","Streaming Audio","Postman Law","CIN","30","S",true,"Brand",""],
["DENPL2630007S","Catching Curveballs_30","Streaming Audio","Postman Law","DEN","30","S",true,"Brand",""],
["MSPPL2630007S","Catching Curveballs_30","Streaming Audio","Postman Law","MSP","30","S",true,"Brand",""],
["CHIPL2630008R","Peace of Mind – One Call for Everything_30","Radio","Postman Law","CHI","30","R",true,"Brand",""],
["CHIPL2630010R","Peace of Mind – One Stop Shop_30","Radio","Postman Law","CHI","30","R",true,"Brand",""],
["CHIPL2615005R","Peace of Mind – No More Chasing Insurance_15","Radio","Postman Law","CHI","15","R",true,"Brand",""],
["CHIPL2615006R","Peace of Mind – We Handle it All_15","Radio","Postman Law","CHI","15","R",true,"Brand",""],
["CINPL2630008R","Peace of Mind – One Call for Everything_30","Radio","Postman Law","CIN","30","R",true,"Brand",""],
["CINPL2630010R","Peace of Mind – One Stop Shop_30","Radio","Postman Law","CIN","30","R",true,"Brand",""],
["CINPL2615005R","Peace of Mind – No More Chasing Insurance_15","Radio","Postman Law","CIN","15","R",true,"Brand",""],
["CINPL2615006R","Peace of Mind – We Handle it All_15","Radio","Postman Law","CIN","15","R",true,"Brand",""],
["DENPL2630008R","Peace of Mind – One Call for Everything_30","Radio","Postman Law","DEN","30","R",true,"Brand",""],
["DENPL2630010R","Peace of Mind – One Stop Shop_30","Radio","Postman Law","DEN","30","R",true,"Brand",""],
["DENPL2615005R","Peace of Mind – No More Chasing Insurance_15","Radio","Postman Law","DEN","15","R",true,"Brand",""],
["DENPL2615006R","Peace of Mind – We Handle it All_15","Radio","Postman Law","DEN","15","R",true,"Brand",""],
["MSPPL2630008R","Peace of Mind – One Call for Everything_30","Radio","Postman Law","MSP","30","R",true,"Brand",""],
["MSPPL2630010R","Peace of Mind – One Stop Shop_30","Radio","Postman Law","MSP","30","R",true,"Brand",""],
["MSPPL2615005R","Peace of Mind – No More Chasing Insurance_15","Radio","Postman Law","MSP","15","R",true,"Brand",""],
["MSPPL2615006R","Peace of Mind – We Handle it All_15","Radio","Postman Law","MSP","15","R",true,"Brand",""],
["MSPPL26DB001O","PL Digital Bulletin - 208x720 - MSP - Cityscape - MinneapolisIA","OOH","Postman Law","MSP","DB","O",true,"Brand",""],
["MSPPL26DB002O","PL Digital Bulletin - 208x720 - MSP - MascotTriangle - MinneapolisIA","OOH","Postman Law","MSP","DB","O",true,"Brand",""],
["MSPPL26DB003O","PL Digital Bulletin - 208x720 - MSP - MascotTriangle - MinneapolisIALogo","OOH","Postman Law","MSP","DB","O",true,"Brand",""]];
