// Creative review endpoint — the approval half of the Campaign Hub loop.
//
// When a station-made (or any) asset needs creative-ops eyes, the app emails
// a review link: /api/review?tok=TOKEN. The reviewer has no staff session, so
// this endpoint is their whole world: GET renders a self-contained review
// page (no app load, no login), POST records their verdict. The token in the
// URL is the credential — a 32-hex random generated by the app when the
// review was sent, matched against appData/assetReviews server-side.
//
// GET  /api/review?tok=...          → HTML review page
// POST /api/review {token, verdict: "approved"|"changes", feedback?}
//
// The main app polls appData/assetReviews and folds responses back into the
// campaign's asset statuses; this endpoint never touches campaigns directly.

const crypto = require('crypto');
const { getSupabase } = require('./_supabase');
const { archiveDoc } = require('./_archive');

function timingSafeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) {
    crypto.timingSafeEqual(bufA, bufA);
    return false;
  }
  return crypto.timingSafeEqual(bufA, bufB);
}

function isValidToken(s) {
  return typeof s === 'string' && /^[A-Fa-f0-9]{16,64}$/.test(s);
}

async function readDoc(supabase, collection, docId) {
  const { data, error } = await supabase
    .from('legacy_docs')
    .select('data')
    .eq('collection', collection)
    .eq('doc_id', docId)
    .maybeSingle();
  if (error) throw error;
  if (!data || data.data == null) return null;
  return typeof data.data === 'string' ? JSON.parse(data.data) : data.data;
}

async function writeDoc(supabase, collection, docId, obj, op) {
  await archiveDoc(supabase, collection, docId, op || 'review', 'api/review');
  const { error } = await supabase
    .from('legacy_docs')
    .upsert(
      { collection, doc_id: docId, data: JSON.stringify(obj), ts: Date.now(), updated_at: new Date().toISOString() },
      { onConflict: 'collection,doc_id' }
    );
  if (error) throw error;
}

// Look the token up without leaking which byte failed: compare against every
// key, keep the match. Tokens are 32-hex randoms, so scanning is fine.
function findReview(reviews, token) {
  let hit = null;
  for (const k of Object.keys(reviews || {})) {
    if (timingSafeEqual(String(token), String(k))) hit = k;
  }
  return hit;
}

const recent = new Map();
const RATE_WINDOW = 60 * 1000;
const MAX_REQ = 30;
function rateLimit(ip) {
  const now = Date.now();
  const arr = (recent.get(ip) || []).filter(t => now - t < RATE_WINDOW);
  arr.push(now);
  recent.set(ip, arr);
  return arr.length > MAX_REQ;
}

const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function sendHtml(res, code, html) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  return res.status(code).send(html);
}

function page(inner) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Creative Review — Doom &amp; Deliverables</title>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,600;0,700;1,500&family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">
<style>
body{margin:0;background:linear-gradient(160deg,#1e1233,#2a1a3e 60%,#1e1233);min-height:100vh;font-family:'DM Sans',sans-serif;color:#E8DFF0;display:flex;align-items:center;justify-content:center;padding:20px}
.card{max-width:560px;width:100%;background:linear-gradient(145deg,#2d1f42,#261840);border:1px solid #4a3565;border-radius:14px;padding:28px;box-shadow:0 8px 40px rgba(30,18,51,.6)}
h1{font-family:'Cormorant Garamond',serif;font-size:26px;margin:0 0 2px;background:linear-gradient(90deg,#E8DFF0,#D4A040);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.meg{font-family:'Cormorant Garamond',serif;font-style:italic;color:#C4A0C8;font-size:14px;margin-bottom:18px}
.row{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #3a2a52;font-size:14px}
.row b{color:#9B8EAD;font-weight:500}
a{color:#4AC8E8}
textarea{width:100%;box-sizing:border-box;margin-top:14px;background:#1e1233;border:1px solid #4a3565;border-radius:8px;color:#E8DFF0;padding:10px;font-family:'DM Sans',sans-serif;font-size:14px;min-height:90px}
.btns{display:flex;gap:10px;margin-top:16px}
button{flex:1;padding:12px;border:none;border-radius:8px;font-size:15px;font-weight:700;cursor:pointer;font-family:'DM Sans',sans-serif}
.ok{background:linear-gradient(135deg,#5BC4A0,#48a486);color:#fff}
.chg{background:linear-gradient(135deg,#E85A7A,#d44868);color:#fff}
.done{padding:14px;border-radius:8px;font-weight:700;text-align:center;margin-top:14px}
.note{font-size:12px;color:#9B8EAD;margin-top:14px;line-height:1.5}
</style></head><body><div class="card">${inner}</div></body></html>`;
}

module.exports = async function handler(req, res) {
  const ip = req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || 'unknown';
  if (rateLimit(String(ip).split(',')[0].trim())) {
    return res.status(429).json({ error: 'Too many requests' });
  }

  let supabase;
  try { supabase = getSupabase(); }
  catch (e) { return res.status(503).json({ error: 'Storage unavailable' }); }

  if (req.method === 'GET') {
    const tok = (req.query && req.query.tok) || '';
    if (!isValidToken(tok)) {
      return sendHtml(res, 400, page('<h1>Creative Review</h1><div class="meg">That link is broken. I would know — I made it.</div><div class="note">The review link appears malformed. Ask for a fresh one.</div>'));
    }
    let reviews;
    try { reviews = (await readDoc(supabase, 'appData', 'assetReviews')) || {}; }
    catch (e) { return sendHtml(res, 500, page('<h1>Creative Review</h1><div class="note">Could not load the review. Try again in a minute.</div>')); }
    const key = findReview(reviews, tok);
    if (!key) {
      return sendHtml(res, 404, page('<h1>Creative Review</h1><div class="meg">No such review. Either it was recalled, or you are lost.</div>'));
    }
    const r = reviews[key];
    const responded = r.status === 'approved' || r.status === 'changes';
    const inner = `
<h1>Creative Review</h1>
<div class="meg">One asset awaits your judgment. Choose wisely — I'm watching.</div>
<div class="row"><b>Campaign</b><span>${esc(r.campName)}${r.brand ? ' · ' + esc(r.brand) : ''}</span></div>
<div class="row"><b>Asset</b><span>${esc(r.assetType)}${r.assetLabel ? ' — ' + esc(r.assetLabel) : ''}</span></div>
${r.due ? `<div class="row"><b>Needed in hand by</b><span>${esc(r.due)}</span></div>` : ''}
${r.trafficDue ? `<div class="row"><b>Traffic goes out</b><span>${esc(r.trafficDue)}</span></div>` : ''}
${r.url ? `<div class="row"><b>File</b><span><a href="${esc(r.url)}" target="_blank" rel="noreferrer">Open the asset ↗</a></span></div>` : '<div class="row"><b>File</b><span>See the attachment in the email that brought you here</span></div>'}
${responded
    ? `<div class="done" style="background:${r.status === 'approved' ? 'rgba(91,196,160,.15)' : 'rgba(232,90,122,.15)'};color:${r.status === 'approved' ? '#5BC4A0' : '#E85A7A'}">Already answered: ${r.status === 'approved' ? '✓ Approved' : 'Changes requested'}${r.feedback ? ' — “' + esc(r.feedback) + '”' : ''}</div><div class="note">This review is closed. If you've changed your mind, reply to the email thread.</div>`
    : `<form method="POST" action="/api/review" onsubmit="this.querySelectorAll('button').forEach(b=>b.disabled=true)">
<input type="hidden" name="token" value="${esc(key)}">
<textarea name="feedback" placeholder="Feedback (required if requesting changes, optional if approving)"></textarea>
<div class="btns">
<button class="ok" name="verdict" value="approved">✓ Approve</button>
<button class="chg" name="verdict" value="changes">Request changes</button>
</div></form>
<div class="note">Your answer flows straight back into Doom &amp; Deliverables — no reply email needed. Sent to you by Emm Caban (Marketing Operations, Atticor).</div>`}
`;
    return sendHtml(res, 200, page(inner));
  }

  if (req.method === 'POST') {
    // Accept both form posts (from the GET page) and JSON.
    let body = req.body || {};
    if (typeof body === 'string') { try { body = JSON.parse(body); } catch (e) { body = {}; } }
    const token = body.token || '';
    const verdict = body.verdict === 'approved' ? 'approved' : body.verdict === 'changes' ? 'changes' : null;
    const feedback = String(body.feedback || '').slice(0, 2000);
    if (!isValidToken(token) || !verdict) return res.status(400).json({ error: 'Invalid request' });
    if (verdict === 'changes' && !feedback.trim()) {
      return sendHtml(res, 200, page('<h1>Hold on</h1><div class="meg">Requesting changes with no feedback? That helps no one.</div><div class="note">Go back and say what needs to change.</div>'));
    }
    let reviews;
    try { reviews = (await readDoc(supabase, 'appData', 'assetReviews')) || {}; }
    catch (e) { return res.status(500).json({ error: 'Storage read failed' }); }
    const key = findReview(reviews, token);
    if (!key) return res.status(404).json({ error: 'Unknown review' });
    if (reviews[key].status === 'approved' || reviews[key].status === 'changes') {
      return sendHtml(res, 200, page('<h1>Already answered</h1><div class="meg">This one is settled. Let it go.</div>'));
    }
    reviews[key] = { ...reviews[key], status: verdict, feedback: feedback.trim(), respondedAt: new Date().toISOString(), applied: false };
    try { await writeDoc(supabase, 'appData', 'assetReviews', reviews, 'respond'); }
    catch (e) { return res.status(500).json({ error: 'Storage write failed' }); }
    const ok = verdict === 'approved';
    return sendHtml(res, 200, page(`<h1>${ok ? 'Approved' : 'Changes requested'}</h1><div class="meg">${ok ? 'Finally, someone with taste. It’s logged.' : 'Noted. The feedback is on its way back.'}</div><div class="done" style="background:${ok ? 'rgba(91,196,160,.15)' : 'rgba(232,90,122,.15)'};color:${ok ? '#5BC4A0' : '#E85A7A'}">${ok ? '✓ Approved' : 'Changes requested'}${feedback ? ' — “' + esc(feedback) + '”' : ''}</div><div class="note">You can close this tab. Doom &amp; Deliverables has it from here.</div>`));
  }

  return res.status(405).json({ error: 'Method not allowed' });
};
